; compile all necessary modules
@setup_nadc.idl

; open file
data_dir = '/data/richardh/NADC/SCIA/L1c/'
flname = 'SCI_NL__1PNPDK20020823_085458_000060492008_00451_02509_0899_new_kd.N1.child'

SCIA_HL_OPEN, data_dir + flname, dsd, status=status
IF status NE 0 THEN NADC_ERR_TRACE

; read States of the Product
SCIA_LV1_RD_STATE, dsd, state, status=status
IF status NE 0 THEN NADC_ERR_TRACE

; read PPG/Etalon Parameters
SCIA_LV1_RD_PPG, dsd, ppg, status=status
IF status NE 0 THEN NADC_ERR_TRACE

; read Sun Reference Spectrum
SCIA_LV1_RD_SRS, dsd, srs, status=status
IF status NE 0 THEN NADC_ERR_TRACE

; read Slit Function Parameters
SCIA_LV1_RD_SFP, dsd, sfp, status=status
IF status NE 0 THEN NADC_ERR_TRACE

; read the calibration options GADS to SciaL1C
SCIA_LV1C_RD_CALOPT, dsd, calopt, status=status
IF status NE 0 THEN NADC_ERR_TRACE

; read Measurement Datasets (Nadir)
SCIA_LV1C_RD_MDS, dsd, mds, type_mds=!nadc.sciaNadir, status=status, state_id=5
IF status NE 0 THEN NADC_ERR_TRACE

; read PMD MDS (NADIR) [example]
SCIA_LV1C_RD_MDS, dsd, mds, type_mds=!nadc.sciaNadir, status=status, $
                  state_id=[6,7], pmd=pmd, /NoMDS
IF status NE 0 THEN NADC_ERR_TRACE

; read Polarisation values (NADIR) [example]
SCIA_LV1C_RD_MDS, dsd, mds, type_mds=!nadc.sciaNadir, status=status, $
                 state_id=7, polV=polV
IF status NE 0 THEN NADC_ERR_TRACE

; close file
;IF SCIA_FCLOSE() NE 0 THEN $
;  MESSAGE, 'FATAL error has occurred in SCIA_FCLOSE'
